### ISSUE TITLE
Error when running tests

### ISSUE THREAD

**Issue by afgoulart** [mobify/nightwatch-commands#37]
Hello,

When I execute `npm test` I get the following error on some tests:

```sh
Error: Cannot find module '/home/andregoulart/projetos/nightwatch-commands/tests/tests/system/site.json'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/andregoulart/projetos/nightwatch-commands/commands/preview.js:29:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

```

Does anyone else get this problem? It seems there's no `.../tests/system/site.json` file.

Thanks in advance!

**Comment by ellenmobify** [comment]
Fixed in 1.3.1.
